class apiRessources :
    productList = '/api/productsList'
    brandList = '/api/brandsList'
    searchProduct = '/api/searchProduct'
    loginValid = '/api/verifyLogin'
    createAccount = '/api/createAccount'
    deleteAccount = '/api/deleteAccount'
    updateAccount = '/api/updateAccount'
    userdetailAccount = '/api/getUserDetailByEmail'